apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthcare-booking-demo.backendServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      {{- include "healthcare-booking-demo.backendPodLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "healthcare-booking-demo.backendPodLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if eq .Values.db.type "mysql" }}
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "healthcare-booking-demo.mysqlServiceName" . }} {{ .Values.db.mysql.servicePort }}; do
                echo "Waiting for MySQL..."
                sleep 2
              done
        {{- else if eq .Values.db.type "postgresql" }}
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "healthcare-booking-demo.postgresServiceName" . }} {{ .Values.db.postgresql.servicePort }}; do
                echo "Waiting for Postgres..."
                sleep 2
              done
        {{- end }}

      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.servicePort }}
          env:
            - name: QUARKUS_HTTP_HOST
              value: "0.0.0.0"

            {{- if eq .Values.db.type "mysql" }}
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "mysql"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:mysql://{{ include "healthcare-booking-demo.mysqlServiceName" . }}:{{ .Values.db.mysql.servicePort }}/{{ .Values.db.mysql.dbName }}"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "healthcare-booking-demo.mysqlServiceName" . }}-secret
                  key: user
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "healthcare-booking-demo.mysqlServiceName" . }}-secret
                  key: password
            - name: QUARKUS_FLYWAY_LOCATIONS
              value: "classpath:db/migration"
            {{- else if eq .Values.db.type "postgresql" }}
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "postgresql"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://{{ include "healthcare-booking-demo.postgresServiceName" . }}:{{ .Values.db.postgresql.servicePort }}/{{ .Values.db.postgresql.dbName }}"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "healthcare-booking-demo.postgresServiceName" . }}-secret
                  key: user
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "healthcare-booking-demo.postgresServiceName" . }}-secret
                  key: password
            - name: QUARKUS_FLYWAY_LOCATIONS
              value: "classpath:db/migration-postgres"
            {{- end }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.servicePort }}
            initialDelaySeconds: 30
            periodSeconds: 10

