{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "healthcare-booking-demo.backendServiceName" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.monitoring.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: healthcare-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /q/metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scheme: http
{{- end }}

