apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: healthcare-backend-servicemonitor
  namespace: healthcare
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: healthcare-backend
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
      scheme: http

